name: Docker

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if docker image build is working
        run: docker build -f Dockerfile .
